// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_switch_output_port_lookup (
ap_uint<256> s_axis_tdata,
ap_uint<32> s_axis_tkeep,
ap_uint<128> s_axis_tuser,
ap_uint<1> s_axis_tvalid,
ap_uint<1> (&s_axis_tready),
ap_uint<1> s_axis_tlast,
ap_uint<256> (&m_axis_tdata),
ap_uint<32> (&m_axis_tkeep),
ap_uint<128> (&m_axis_tuser),
ap_uint<1> (&m_axis_tvalid),
ap_uint<1> m_axis_tready,
ap_uint<1> (&m_axis_tlast),
ap_uint<1> reset);
